AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_sold

  Powertools example

Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.12

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  PlaceBidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: place_bid.lambda_handler
      CodeUri: src
      Description: Place Bid function
      Architectures:
        - x86_64
#      Tracing: Active
      Events:
        PlaceBidPath:
          Type: Api
          Properties:
            Path: /bid
            Method: post
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ProcessBidQueue.Arn
      Environment:
        Variables:
          BID_QUEUE_URL: !Ref ProcessBidQueue
    DependsOn: PlaceBidFunctionLogGroup

  ProcessBidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process_bid.lambda_handler
      CodeUri: src
      Description: Process Bid Queue Worker
      Architectures:
        - x86_64
      Timeout: 30
      ReservedConcurrentExecutions: 1
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt ProcessBidQueue.Arn
            BatchSize: 10
#            MaximumBatchingWindowInSeconds: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref ProcessBidQueue
        - SQSSendMessagePolicy:
            QueueName: !Ref ProcessBidDeadLetterQueue
        - DynamoDBCrudPolicy:
            TableName: !Ref BidsTable
      Environment:
        Variables:
          BID_QUEUE_URL: !Ref ProcessBidQueue
          BIDS_TABLE: !Ref BidsTable
    DependsOn: ProcessBidFunctionLogGroup

  PlaceBidFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:  /aws/lambda/PlaceBidFunction
      RetentionInDays: 1

  ProcessBidFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:  /aws/lambda/ProcessBidFunction
      RetentionInDays: 1

  ProcessBidQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-bid-queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessBidDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessBidDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-bid-queue-dlq"

  BidsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SamSoldBids
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

Outputs:
  BidQueueName:
    Description: "Name of the bid queue"
    Value: !GetAtt ProcessBidQueue.QueueName