AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.12
    LoggingConfig:
      LogFormat: JSON
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  PlaceBidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: place_bid.lambda_handler
      CodeUri: ../src
      Layers:
        - !Ref SamSoldLayer
      Description: Place Bid function
      Architectures:
        - x86_64
      Events:
        PlaceBidPath:
          Type: Api
          Properties:
            Path: /bid
            Method: post
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ProcessBidQueue.Arn
      Environment:
        Variables:
          BID_QUEUE_URL: !Ref ProcessBidQueue

  LotApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lot_api.lambda_handler
      CodeUri: ../src
      Layers:
        - !Ref SamSoldLayer
      Description: Resources API for Lot
      Architectures:
        - x86_64
      Events:
        GetLotPath:
          Type: Api
          Properties:
            Path: /lots/{lot_id}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue SamSold-BidsTable
      Environment:
        Variables:
          BIDS_TABLE: !ImportValue SamSold-BidsTable

  ProcessBidFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process_bid.lambda_handler
      CodeUri: ../src
      Layers:
        - !Ref SamSoldLayer
      Description: Process Bid Queue Worker
      Architectures:
        - x86_64
      Timeout: 30
      ReservedConcurrentExecutions: 1
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt ProcessBidQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref ProcessBidQueue
        - SQSSendMessagePolicy:
            QueueName: !Ref ProcessBidDeadLetterQueue
        - DynamoDBCrudPolicy:
            TableName: !ImportValue SamSold-BidsTable
      Environment:
        Variables:
          BID_QUEUE_URL: !Ref ProcessBidQueue
          BIDS_TABLE: !ImportValue SamSold-BidsTable

  BroadcastLotChangesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: broadcast_lot_changes.lambda_handler
      Layers:
        - !Ref SamSoldLayer
      Events:
        DynamoStream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue SamSold-BidsTable-StreamArn
            StartingPosition: LATEST
            BatchSize: 5
            MaximumRetryAttempts: 2
            Enabled: true
            FilterCriteria:
              Filters:
                - Pattern: >
                    {
                      "eventName": ["MODIFY"],
                      "dynamodb": {
                        "Keys": {
                          "PK": {
                            "S": [{"prefix": "LOT#"}]
                          }
                        }
                      }
                    }



  SamSoldLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}_core-dependencies"
      Description: Common Python dependencies
      ContentUri: ../layers/sam_sold_dependencies
      CompatibleRuntimes:
        - python3.12
    DeletionPolicy: Delete

  PlaceBidFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PlaceBidFunction}"
      RetentionInDays: 1

  ProcessBidFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProcessBidFunction}"
      RetentionInDays: 1

  LotApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LotApiFunction}"
      RetentionInDays: 1

  BroadcastLotChangesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${BroadcastLotChangesFunction}"
      RetentionInDays: 1

  ProcessBidQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-bid-fifo-queue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessBidDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessBidDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-bid-fifo-queue-dlq.fifo"
      FifoQueue: true

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for for Hello World
      Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
